# -*- coding: utf-8 -*-
"""supply graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKABZ6T4hxbuUcRLFmO9jCXSKPt7NtUm
"""

!pip install torch-geometric-temporal

import pandas as pd
import numpy as np
import torch
from torch_geometric_temporal.signal import StaticGraphTemporalSignal, temporal_signal_split
from torch_geometric.data import HeteroData
from torch_geometric.nn import HeteroConv, GCNConv
import matplotlib.pyplot as plt

plant_edges = pd.read_csv("/content/drive/MyDrive/Supply_Graph/SupplyGraph-main/Raw Dataset/Homogenoeus/Edges/EdgesIndex/Edges (Plant).csv")

production = pd.read_csv("/content/drive/MyDrive/Supply_Graph/SupplyGraph-main/Raw Dataset/Homogenoeus/Temporal Data/Weight/Production .csv")

production.drop("Date",axis = 1,inplace = True)

d = {}
for i in range(len(production.columns)):
  d[production.columns[i]] = i

d

production.rename(columns = d,inplace = True)

rolled_prod = production.rolling(window = 30).mean()

rolled_prod = rolled_prod.drop(axis = 0,index = [x for x in range(30)])

rolled_prod.reset_index(drop = True,inplace = True)

rolled_prod

plt.plot(rolled_prod[:40],label = "Production")
plt.legend()
plt.show()

data = pd.read_csv("/content/drive/MyDrive/Supply_Graph/SupplyGraph-main/Code/Developing heterogeneous graph/data.csv")

data

df = pd.read_csv("/content/drive/MyDrive/Supply_Graph/SupplyGraph-main/Raw Dataset/Homogenoeus/Edges/EdgesIndex/Edges (Plant).csv")  # columns: Plant, node1, node2

src = torch.tensor(df["node1"].values, dtype=torch.long)
dst = torch.tensor(df["node2"].values, dtype=torch.long)

# undirected version
edge_index = torch.stack(
    [torch.cat([src, dst]), torch.cat([dst, src])],
    dim=0
)

# all nodes that appear in the full graph
nodes = torch.unique(torch.cat([src, dst]))

# later: use NodesIndex.csv to align these ids with your feature matrix X

edge_index

data = HeteroData()

# 1) Product nodes
nodes_idx = pd.read_csv("/content/drive/MyDrive/Supply_Graph/SupplyGraph-main/Raw Dataset/Homogenoeus/Nodes/NodesIndex.csv")  # gives all product indices
num_prod = len(nodes_idx)
prod_feat_dim = 16  # choose

data['rolled_prod'].x = torch.randn(num_prod, prod_feat_dim)

def load_edge_index(path):
    df = pd.read_csv(path)           # these have columns: Plant/ProductGroup/etc + node1 + node2
    src = torch.tensor(df['node1'].values, dtype=torch.long)
    dst = torch.tensor(df['node2'].values, dtype=torch.long)
    return torch.stack([src, dst], dim=0)

# 2) Add all relation types

base = "/content/drive/MyDrive/Supply_Graph/SupplyGraph-main/Raw Dataset/Homogenoeus/Edges/EdgesIndex/"

data['rolled_prod', 'same_plant', 'product'].edge_index = \
    load_edge_index(base + "Edges (Plant).csv")

data['rolled_prod', 'same_storage', 'product'].edge_index = \
    load_edge_index(base + "Edges (Storage Location).csv")

data['rolled_prod', 'same_product_group', 'product'].edge_index = \
    load_edge_index(base + "Edges (Product Group).csv")

data['rolled_prod', 'same_product_subgroup', 'product'].edge_index = \
    load_edge_index(base + "Edges (Product Sub-Group).csv")

data

import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.nn import HeteroConv, GCNConv, SAGEConv
from torch_geometric_temporal.signal import StaticGraphTemporalSignal, temporal_signal_split

# ------------------------------------------------------------------
# 0. Assume you ALREADY created this HeteroData object:
#
# data = HeteroData(
#   product={ x=[41, 16] },
#   (product, same_plant, product)={ edge_index=[2, 1647] },
#   (product, same_storage, product)={ edge_index=[2, 3046] },
#   (product, same_product_group, product)={ edge_index=[2, 188] },
#   (product, same_product_subgroup, product)={ edge_index=[2, 52] }
# )
#
# and that data['product'].x is aligned with NodesIndex.csv
# ------------------------------------------------------------------

# ---------- 1. Load temporal Unit/Production .csv as node time series ----------
ROOT = "/content/drive/MyDrive/Supply_Graph/SupplyGraph-main/Raw Dataset/Homogenoeus/Temporal Data/Unit"
PROD_CSV = os.path.join(ROOT, "Production .csv")  # note space before .csv[page:62]

prod_df = pd.read_csv(PROD_CSV)
# Expected structure (as in coding_directions.md):
#   Date, P1, P2, ..., one column per product, matching NodesIndex order.[page:1]

# Separate date and values
date_col = "Date"
assert date_col in prod_df.columns
dates = prod_df[date_col].values
prod_df = prod_df.drop(columns=[date_col])


# Ensure product column order matches your 41 products
# If you used NodesIndex.csv to define product order:
#   nodes_idx_df = pd.read_csv("Raw Dataset/Homogenoeus/Nodes/NodesIndex.csv")
#   product_ids = nodes_idx_df["Node"].tolist()
# and you must reorder columns:
# prod_df = prod_df[product_ids]

values = rolled_prod.values.astype(np.float32)  # [T, num_products]
T, num_nodes = values.shape

assert num_nodes == data['rolled_prod'].x.size(0), "Products mismatch between graph and temporal data"

# Build (features, targets) for 1-step-ahead forecasting
# features[t] = production at time t, targets[t] = production at time t+1
X = values[:-1]   # [T-1, N]
Y = values[1:]    # [T-1, N]

features = X.reshape((X.shape[0], num_nodes, 1))  # [T-1, N, 1]
targets  = Y.reshape((Y.shape[0], num_nodes, 1))  # [T-1, N, 1]

# ---------- 2. Use ONE merged edge_index with all relation types for temporal signal ----------
# (We still keep hetero edge types for the model itself.)
edge_indices = []
for _, ei in data.edge_index_dict.items():
    edge_indices.append(ei)
edge_index_homo = torch.cat(edge_indices, dim=1)  # [2, E_total]
edge_index_np = edge_index_homo.cpu().numpy()
edge_weight = np.ones((edge_index_np.shape[1], 1), dtype=np.float32)

dataset = StaticGraphTemporalSignal(
    edge_index=edge_index_np,
    edge_weight=edge_weight,
    features=[f for f in features],   # list of [N, 1]
    targets=[t for t in targets],     # list of [N, 1]
)

train_dataset, test_dataset = temporal_signal_split(dataset, train_ratio=0.8)

# ---------- 3. Heterogeneous GCN over the four relation types ----------
class HeteroGCN(nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super().__init__()
        # Correct the destination node type to 'rolled_prod' for consistency with input features
        self.conv1 = HeteroConv({
            ('rolled_prod', 'same_plant', 'rolled_prod'): SAGEConv(in_channels, hidden_channels),
            ('rolled_prod', 'same_storage', 'rolled_prod'): SAGEConv(in_channels, hidden_channels),
            ('rolled_prod', 'same_product_group', 'rolled_prod'): SAGEConv(in_channels, hidden_channels),
            ('rolled_prod', 'same_product_subgroup', 'rolled_prod'): SAGEConv(in_channels, hidden_channels),
        }, aggr='sum')

        self.conv2 = HeteroConv({
            ('rolled_prod', 'same_plant', 'rolled_prod'): SAGEConv(hidden_channels, hidden_channels),
            ('rolled_prod', 'same_storage', 'rolled_prod'): SAGEConv(hidden_channels, hidden_channels),
            ('rolled_prod', 'same_product_group', 'rolled_prod'): SAGEConv(hidden_channels, hidden_channels),
            ('rolled_prod', 'same_product_subgroup', 'rolled_prod'): SAGEConv(hidden_channels, hidden_channels),
        }, aggr='sum')

        self.lin = nn.Linear(hidden_channels, out_channels)

    def forward(self, x_dict, edge_index_dict):
        # Transform edge_index_dict keys to be consistent with 'rolled_prod' as destination node type
        transformed_edge_index_dict = {}
        for (src_type, rel_type, dst_type), edge_index_tensor in edge_index_dict.items():
            if dst_type == 'product':
                transformed_edge_index_dict[(src_type, rel_type, 'rolled_prod')] = edge_index_tensor
            else:
                transformed_edge_index_dict[(src_type, rel_type, dst_type)] = edge_index_tensor

        x_dict = self.conv1(x_dict, transformed_edge_index_dict)
        x_dict = {k: F.relu(v) for k, v in x_dict.items()}
        x_dict = self.conv2(x_dict, transformed_edge_index_dict)
        x_dict = {k: F.relu(v) for k, v in x_dict.items()}
        out = self.lin(x_dict['rolled_prod'])  # [N, out_channels]
        return out

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

static_x = data['rolled_prod'].x.to(device)   # [N, 16]
in_channels = static_x.size(1) + 1        # static 16 + 1 temporal scalar
model = HeteroGCN(in_channels, hidden_channels=32, out_channels=1).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

data = data.to(device)

# Transform data.edge_index_dict once before the training loop
transformed_data_edge_index_dict = {}
for (src_type, rel_type, dst_type), edge_index_tensor in data.edge_index_dict.items():
    if dst_type == 'product':
        transformed_data_edge_index_dict[(src_type, rel_type, 'rolled_prod')] = edge_index_tensor
    else:
        transformed_data_edge_index_dict[(src_type, rel_type, dst_type)] = edge_index_tensor

# ---------- 5. Evaluation ----------
def asymmetric_loss(y_hat, y_true, alpha=2.0):
    # alpha > 1 → under-prediction punished more
    diff = y_hat - y_true
    under_mask = (diff < 0).float()      # y_hat < y_true
    over_mask  = (diff >= 0).float()     # y_hat >= y_true

    under_loss = (diff ** 2) * alpha * under_mask
    over_loss  = (diff ** 2) * over_mask

    return (under_loss + over_loss).mean()

# ---------- 4. Training loop ----------
for epoch in range(50):
    model.train()
    total_loss = 0.0
    for snapshot in train_dataset:
        temporal_x = torch.tensor(snapshot.x, dtype=torch.float32, device=device)  # [N, 1]
        y_true = torch.tensor(snapshot.y, dtype=torch.float32, device=device)      # [N, 1]

        # concat static + temporal feature
        x_cat = torch.cat([static_x, temporal_x], dim=-1)  # [N, 17]
        x_dict = {'rolled_prod': x_cat}

        # Pass the transformed edge_index_dict to the model
        y_hat = model(x_dict, transformed_data_edge_index_dict)        # [N, 1]


        loss = asymmetric_loss(y_hat, y_true)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1}, train MSE: {total_loss / len(train_dataset.features):.4f}")



model.eval()
with torch.no_grad():
    mse_list = []
    for snapshot in test_dataset:
        temporal_x = torch.tensor(snapshot.x, dtype=torch.float32, device=device)
        y_true = torch.tensor(snapshot.y, dtype=torch.float32, device=device)
        x_cat = torch.cat([static_x, temporal_x], dim=-1)
        x_dict = {'rolled_prod': x_cat}
        # Pass the transformed edge_index_dict to the model
        y_hat = model(x_dict, transformed_data_edge_index_dict)
        mse = asymmetric_loss(y_hat, y_true, alpha=2.0).item()
        mse_list.append(mse)

    print(f"Test MSE: {np.mean(mse_list):.4f}")

y_hat-y_true

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score,root_mean_squared_error

features.shape

mse_ = mean_squared_error(y_true, y_hat)
mae_ = mean_absolute_error(y_true, y_hat)
r_2 = r2_score(y_true, y_hat)
rmse = root_mean_squared_error(y_true, y_hat)
print("\n",mse_,"\n", mae_,"\n",r_2,"\n",rmse,"\n")



